### ISSUE TITLE
Metric evaluation error: y_true and y_pred contain different number of classes

### ISSUE THREAD

**Issue by nicl-nno** [aimclub/FEDOT#1016]
The problem "Metric evaluation error: y_true and y_pred contain different number of classes 45, 85" raises for click_prediction_small dataset

Looks like class stratification is failing.

**Comment by curiousHG** [comment]
Can you expand on the issue? Or maybe narrow down to which file or code the problem is?

**Comment by nicl-nno** [comment]
@curiousHG 

This problem occurs for classification tasks when the number of classes is very large and cross-validation fails to preserve the examples for all classes.

The connected problems are for <2 classes in sample and new classes in predict sample.

**Comment by gkirgizov** [comment]
Duplicate of #954

**Comment by gkirgizov** [comment]
Duplicate of https://github.com/aimclub/FEDOT/issues/954
