### ISSUE TITLE
Update tuning documentation

### ISSUE THREAD

**Issue by MorrisNein** [aimclub/FEDOT#1071]
Source:
docs/source/advanced/hyperparameters_tuning.rst

- Reference to seemingly deleted class `PipelineTuner` must be updated.
- Perhaps, it should reference [GOLEM tuning documentation](https://thegolem.readthedocs.io/en/latest/api/tuning.html).
- All mentions of GOLEM or FEDOT classes should maintain the following format (since #1067 you can reference GOLEM classes too): 
```
:doc:`~path.to.Class`
```

**Comment by nicl-nno** [comment]
@YamLyubov посмотри плз актуально ли это
