### ISSUE TITLE
initial assumptions for ts

### ISSUE THREAD

**Issue by maypink** [aimclub/FEDOT#1074]
In [this ](fedot/core/pipelines/verification.py) PR `initial_assumption` with smoothing+autoregression was removed due to `Unable to allocate 44.9 GiB for an array with shape (2010082226, 3) and data type float64` on `fit_pipeline` stage in `test_pseudo_remote_composer_ts_forecasting` test. There is a need to figure out what causes this error and fix it.

**Comment by kasyanovse** [comment]
There is no problem with test now.
Initial assumption with smoothing+autoregression is added in https://github.com/aimclub/FEDOT/pull/1153.
