### ISSUE TITLE
pipelines with numbers 

### ISSUE THREAD

**Issue by GrigoriJasnovidov** [aimclub/FEDOT#1084]
#The following script makes pipelines with numbers sometimes.

from golem.core.optimisers.genetic.operators.mutation import Mutation
from golem.core.optimisers.genetic.gp_params import GPAlgorithmParameters
from golem.core.optimisers.optimization_parameters import GraphRequirements
from golem.core.optimisers.optimizer import GraphGenerationParams, AlgorithmParameters

gr = GraphRequirements()
gap = GPAlgorithmParameters()
ggp = GraphGenerationParams()
m = Mutation(parameters = gap,    requirements= gr,  graph_generation_params = ggp)

#model - a fitted ts-forecasting model
#take some individual
ind = model.history.individuals[-2][0]

#mutation
x = m._mutation(ind)
x

**Comment by valer1435** [comment]
Думаю, что проблема в том, что в примере используются сущности из голема, а надо из федота. Например, как в этом (https://github.com/aimclub/FEDOT/blob/master/test/unit/optimizer/gp_operators/test_mutation.py#L41) тесте

**Comment by GrigoriJasnovidov** [comment]
Спасибо, теперь все работает)
