### ISSUE TITLE
Pipeline fitting errors after mutations

### ISSUE THREAD

**Issue by GrigoriJasnovidov** [aimclub/FEDOT#1086]
pipeline obtained in the last line does not fit always well. Sometimes fittig goes well, sometimes ValueError appears.
model - is a fitted fedot model, train_input - a given train_input for model

```
from fedot.core.pipelines.adapters import PipelineAdapter
from fedot.core.pipelines.pipeline_composer_requirements import PipelineComposerRequirements
from fedot.core.pipelines.pipeline_graph_generation_params import get_pipeline_generation_params
from golem.core.dag.verification_rules import DEFAULT_DAG_RULES
from golem.core.optimisers.genetic.gp_params import GPAlgorithmParameters
from golem.core.optimisers.genetic.operators.mutation import Mutation, MutationStrengthEnum

task = Task(TaskTypesEnum.ts_forecasting)
operations = ['ridge','lagged','sparse_lagged']
requirements = PipelineComposerRequirements(primary=operations, secondary=operations)
graph_params = get_pipeline_generation_params(requirements=requirements,
                                                  rules_for_constraint=DEFAULT_DAG_RULES, task=task)
parameters = GPAlgorithmParameters(mutation_strength=MutationStrengthEnum.strong, mutation_prob=1)

mutation = Mutation(parameters, requirements, graph_params)

ind = model.history.individuals[-2][0]
x = mutation._mutation(ind)
p = PipelineAdapter().restore(x.graph)
p.fit(train_input)
```

**Comment by nicl-nno** [comment]
>sometimes ValueError appears

Так а какие именно-то?

**Comment by GrigoriJasnovidov** [comment]
Бывает такое:
![Снимок экрана (591)](https://user-images.githubusercontent.com/91132144/233067405-0d1c570a-f30f-4915-9b94-0cb2c4bf687b.png)
![Снимок экрана (592)](https://user-images.githubusercontent.com/91132144/233067406-938e65a4-531a-4af7-a4b5-d2e1ad6392db.png)

Если добавить в operations какие-нибудь более сложные операции, например, 'arima' то частота ошибок возрастает.

**Comment by valer1435** [comment]
Можешь показать получающиеся пайплайны? Тут проблема в том, что мутации сами по себе не учитывают несовместимость некоторых операций (только частично). Чтобы фильтровать неправильные графы, существует специальная [сущность](https://github.com/aimclub/GOLEM/blob/main/golem/core/dag/graph_verifier.py#L16). Здесь [пример ](https://github.com/aimclub/GOLEM/blob/main/golem/core/optimisers/genetic/operators/mutation.py#L50) использования в големе.

**Comment by GrigoriJasnovidov** [comment]
Вот пайплайны + соответствующие ошибки:
![Снимок экрана (593)](https://user-images.githubusercontent.com/91132144/233107008-cd3d0656-14bf-4544-ab93-e82479446ba5.png)
![Снимок экрана (594)](https://user-images.githubusercontent.com/91132144/233107013-52b85430-6cda-4fb1-9dff-7c78161baf1d.png)
![Снимок экрана (595)](https://user-images.githubusercontent.com/91132144/233107015-e1808836-346c-4bcf-adec-e52ba9d13926.png)
![Снимок экрана (596)](https://user-images.githubusercontent.com/91132144/233107018-6a75db60-dcb2-4faa-98a3-1aad8b23ffa3.png)

Вроде бы когда я у экземпляра класса Mutation вызываю метод ._mutation пайплайны же должны автоматически строиться допустимым образом?

**Comment by valer1435** [comment]
>Вроде бы когда я у экземпляра класса Mutation вызываю метод ._mutation пайплайны же должны автоматически строиться допустимым образом?

Нет. Мы хотим разделить ответственность между мутациями и проверками пайплайна. Поэтому это две разные сущности. Что касается именно временных рядов, они требуют дополнительных [правил проверки](https://github.com/aimclub/FEDOT/blob/master/fedot/core/pipelines/verification_rules.py#L155). Наслаивание условий проверок в каждой мутации приведет к невероятному усложнению и запутыванию кода. 

Если не понятно, откуда берутся такие правила для временных рядов - могу объяснить (как я это задумывал) лично.

PS На скринах действительно неправильные пайплайны, Verifier их отсеивает
