### ISSUE TITLE
Error in `data_has_categorical_features` with supplementary_data

### ISSUE THREAD

**Issue by aPovidlo** [aimclub/FEDOT#1094]
Возникает ошибка в функции [`data_has_categorical_features`](https://github.com/aimclub/FEDOT/blob/f02b6262adfbd1d7052e4456b953f2848f6cda42/fedot/core/data/data_preprocessing.py#L127), лог примерно такой :

![image](https://user-images.githubusercontent.com/22475542/236010753-4bed294a-3917-4e7b-b5c1-231445003d7f.png)
![image](https://user-images.githubusercontent.com/22475542/236010796-10e2631a-6d23-4eaa-b394-c33ea091849f.png)

Код для воспроизведения:
```
  problem = 'classification'

  train = pd.read_csv(f'{fedot_project_root()}/cases/data/scoring/scoring_train.csv')
  test = pd.read_csv(f'{fedot_project_root()}/cases/data/scoring/scoring_test.csv')

  input_train = InputData(
      idx=np.arange(0, len(train.target)),
      features=np.array(train.drop(['target'], axis=1)),
      target=np.array(train.target),
      task=Task(TaskTypesEnum.classification),
      data_type=DataTypesEnum.table,
  )

  input_test = InputData(
      idx=np.arange(0, len(test.target)),
      features=np.array(test.drop(['target'], axis=1)),
      target=np.array(test.target),
      task=Task(TaskTypesEnum.classification),
      data_type=DataTypesEnum.table,
  )

  init_pipeline = PipelineBuilder() \
      .add_node(operation_type='rf', params=None) \
      .build()

  model = Fedot(
      problem=problem,
      timeout=0.001,
      metric='roc_auc',
      initial_assumption=init_pipeline,
      use_input_preprocessing=False
  )

  model.fit(input_train)
  predicted = model.predict(input_test)
```

**Comment by valer1435** [comment]
Оказывается, в pipelineBuilder'e тоже есть поле use_input_preprocessing. Если использовать федот вместе с начальным приближением, у них должны быть одинаковыми эти параметры

`init_pipeline = PipelineBuilder(use_input_preprocessing=False) \
  .add_node(operation_type='rf', params=None) \
  .build()`
  
  Так работает, но падает на том, что в rf попадают наны (а они в данных действительно есть)
  
  Не знаю как это править и стоит ли вообще править.
