### ISSUE TITLE
Fix integration tests (v 0.7.1)

### ISSUE THREAD

**Issue by gkirgizov** [aimclub/FEDOT#1110]
A respectful issue.

As now tests badge is on the main project page -- they must be more predictable, don't fall stochastically. 
And even if they must be stochastic -- let's run them multiple times and estimate required number of times they finish with positive results.

[Failing tests from the last run on v0.7.1.](https://github.com/aimclub/FEDOT/actions/runs/5208782899/jobs/9397780459)
```
=========================== short test summary info ============================
FAILED test/integration/quality/test_quality_improvement.py::test_classification_quality_improvement - assert 0.816 >= 0.823
FAILED test/integration/quality/test_quality_improvement.py::test_multiobjective_improvement - IndexError: list index out of range
FAILED test/integration/real_applications/test_examples.py::test_api_example - ValueError: Must pass 2-d input. shape=()
FAILED test/integration/real_applications/test_examples.py::test_multi_modal_example - ValueError: No data for primary node tfidf
FAILED test/integration/real_applications/test_real_cases.py::test_credit_scoring_problem - ValueError: array must not contain infs or NaNs
========== 5 failed, 213 passed, 6250 warnings in 2379.71s (0:39:39) ===========
```

**Comment by IIaKyJIuH** [comment]
Проблема, которая препятствует разрешению, связана с GOLEM и находится в следующем методе [Dispatcher'а](https://github.com/aimclub/GOLEM/blob/main/golem/core/optimisers/genetic/evaluation.py#L196-L201):
![image](https://github.com/aimclub/FEDOT/assets/38308131/af4c6205-2fa0-4ce1-9c2d-6d84491f5d1c)

Воспроизводится в FEDOT на тесте [test/integration/test_main_api_params.py::test_timeout](https://github.com/aimclub/FEDOT/blob/master/test/integration/api_params/test_main_api_params.py#L45-L71)

**Comment by nicl-nno** [comment]
В тесте в конфиге указано что:

        'pop_size': 1,

Есть ли вообще смысл в такой настройке - для эволюции это достаточно вырожденный случай. 
Если поставить 2, то у меня тест проходит.

**Comment by nicl-nno** [comment]
Можно в GOLEM добавить issue на корректную обработку краевых значений - но вроде это не тот сценарий, который есть смысл интеграционно тестировать в fedot-е.

**Comment by gkirgizov** [comment]
Согласен с Колей. Можно поставить 2 и закрыть вопрос. А вообще, даже при pop_size=1 должна передаваться популяция, то есть список, пусть и из 1 элемента. Почему это не так -- посмотрю
