### ISSUE TITLE
Refactor MultiOperationsHPAnalyze

### ISSUE THREAD

**Issue by maypink** [aimclub/FEDOT#1135]
This PR is a part of refactoring Sensitivity Analysis in FEDOT. The main goals are:

- [ ] Refactor `MultiOperationsHPAnalyze` and consider transferring this module to GOLEM
- [ ] Rewrite documentation for SA
- [ ] Cover `MultiOperationsHPAnalyze` module with tests

**Comment by nicl-nno** [comment]
@maypink актуально или можно закрыть?

**Comment by maypink** [comment]
> @maypink актуально или можно закрыть?

актуально, но себя я с нее уберу, мб у кого-то другого руки быстрее дойдут
