### ISSUE TITLE
train_test_data_setup does not support split_ratio for timeseries

### ISSUE THREAD

**Issue by kasyanovse** [aimclub/FEDOT#1146]
Now only validation_blocks is used. Split_ratio for timeseries may be defined only in DataSourceSplitter.

**Comment by valer1435** [comment]
А нужна ли эта функциональность вообще? Проще задать длину прогноза в абсолютных значениях, чем в процентах от длины ряда

**Comment by nicl-nno** [comment]
Для задач, где рядов много и нужно с ними работать в режиме бенчмарка - может быть полезно.

**Comment by kasyanovse** [comment]
По идее для разбиения данных можно использовать либо `split_ratio`, либо `validation_blocks`. Однако когда `validation_blocks = None`, данные готовятся для `out-of-sample` предсказания и никакой `split_ratio` не нужен. Когда `validation_blocks` определен, то `split_ratio` также не нужен. В общем, этот параметр на текущий момент не нужен.
