### ISSUE TITLE
Interactive examples for FEDOT

### ISSUE THREAD

**Issue by edublancas** [aimclub/FEDOT#1169]
Hi FEDOT team!

My team maintains a few [open-source](https://github.com/ploomber/jupysql) projects, and we've seen that having interactive examples greatly helps newcomers! We're maintaining a Binder cluster that provides ephemeral JupyterLab sessions ([example](https://binder.ploomber.io/v2/gh/ploomber/jupysql/master?urlpath=lab/tree/doc/quick-start.md)). It essentially spins up a JupyterLab session with pre-made examples.

We're happy to sponsor FEDOT with some computing power. If you're interested, please get in touch with me! (my contact info is in my [profile](https://github.com/edublancas/))

**Comment by nicl-nno** [comment]
Hu Eduardo!

It is quite for us interesting to provide the examples of FEDOT usage for the Binder users.

Now have the set of pre-evaluated [notebooks](https://github.com/ITMO-NSS-team/fedot-examples) for different tasks.

I will re-check the existing examples and contact you via email about the details of integration with Binder.

**Comment by edublancas** [comment]
sounds good!

**Comment by edublancas** [comment]
Hi, following up here

I went ahead and enabled our binder cluster for pyRiemann: https://binder.ploomber.io/v2/gh/aimclub/FEDOT/master?filepath=examples

It's giving some issues because of the multiple requirement files:

```
Step 4/11 : RUN cat other_requirements/extra.txt >> /home/FEDOT/requirements.txt
 ---> Running in e12be8d133de
cat: other_requirements/extra.txt: No such file or directory
Removing intermediate container e12be8d133de
```

seems like binder is automatically trying to infer which are the requirements to install, but we can configure it to avoid this issue. 

Happy to open a PR to get this up and running!
