### ISSUE TITLE
Fedot cannot interpret n_jobs < -1

### ISSUE THREAD

**Issue by kasyanovse** [aimclub/FEDOT#1170]

**Comment by nicl-nno** [comment]
Вообще можно ронять ошибку в таком случае.

**Comment by kasyanovse** [comment]
По идее это валидное значение. -1 - это все ядра, -2 - это все без одного, -3 - все без двух и т.д.
Сейчас федот некорректно рассчитывает время композиции и не проводит ее вообще.

**Comment by nicl-nno** [comment]
>-2 - это все без одного, -3 - все без двух и т.д.

Не сталкивался с таким. Это в sklearn так?

**Comment by kasyanovse** [comment]
В joblib.
Очень удобная штука.

**Comment by nicl-nno** [comment]
Ок. Ну можно и поддержать, конечно.
