### ISSUE TITLE
Annoing Fedot task params

### ISSUE THREAD

**Issue by kasyanovse** [aimclub/FEDOT#1178]
Fedot has two annoing params: `problem` and `task_params` that can be defined as `Task` type.
Also `Data` type has `data_type` and `task` params.
Maybe Fedot can get task information from data?

**Comment by valer1435** [comment]
Если мы будем на полную использовать методы загрузки инпутдаты из csv, каринок, текста, датафреймов и так далее, то необходимость задавать инпутдату вручную в целом должна пропасть
