### ISSUE TITLE
Automated window size selection

### ISSUE THREAD

**Issue by valer1435** [aimclub/FEDOT#1190]
If we want to implement this approach in fedot we need to consider aspects and limitations below:
1) We would get different window size in each cv fold that will affect on dimension for following models, if we will choose window size for each fold
2) We would get inappropriate window size for csv folds if we will choose window size based on a whole train time series. (Chosen window size might be bigger than fold length)
3) How we should implement this technique? In lagged operation directly or as standalone module?

**Comment by valer1435** [comment]
>Окно можно выбрать на самом маленьком фолде в кросс валидации (первый). Сохранить в узле lagged и больше не трогать.

При таком подходе теряем возможность подстроиться под более новые данные. 

Но при подсчете на всем ряду получается своего рода даталик, когда мы смотрим на весь ряд, получаем из него информацию и потом используем для обучения на фолдах

**Comment by valer1435** [comment]
Я бы попробовал менять его при каждом вызове fit

**Comment by kasyanovse** [comment]
> При таком подходе теряем возможность подстроиться под более новые данные.

А зачем под них подстраиваться? Размер окна - гиперпараметр, а не параметр модели. Хотя в некоторые модели можно его добавить на уровне параметра, выбираемого при обучении.

> Но при подсчете на всем ряду получается своего рода даталик, когда мы смотрим на весь ряд, получаем из него информацию и потом используем для обучения на фолдах

Если окно - гиперпараметр, то утечки данных быть не должно.
