### ISSUE TITLE
CGRU-related error

### ISSUE THREAD

**Issue by nicl-nno** [aimclub/FEDOT#1240]
Test test_cgru_forecasting and test_cgru_in_pipeline are failing due to the 

![image](https://github.com/aimclub/FEDOT/assets/5711814/d9057df1-126d-471c-a798-4928913409a4)

Now they are temporary disabled.

**Comment by kasyanovse** [comment]
Also `test_models_does_not_fall_on_constant_data` falls with `cgru`.
