### ISSUE TITLE
enh: `giotto_tda` and `risper` -> other_requirements

### ISSUE THREAD

**Issue by aPovidlo** [aimclub/FEDOT#1259]
## Summary

Modules `giotto_tda` and `risper`  requires to migrate to `other_requirements` for advantage Time Series, due to fact, that `risper` has dependence of C++.

**Comment by valer1435** [comment]
Воспроизводимость зависит от того, стоит ли build tools. Вообще такие зависимости действительно неприятны. Наверное стоит делать проверку на наличие у юзера этого пакета перед выбором пресета.

**Comment by valer1435** [comment]
https://github.com/aimclub/FEDOT/pull/1261
