### ISSUE TITLE
Python 3.12 support

### ISSUE THREAD

**Issue by e-kondr01** [aimclub/FEDOT#1260]
Trying to install Fedot on Python 3.12, I get the following error trying to resolve dependencies:

```
- sktime requires Python <3.12,>=3.7, so it will not be satisfied for Python >=3.12.1,<3.13.0

Because no versions of fedot match >0.7.3,<0.8.0
 and fedot (0.7.3) depends on sktime (0.16.1), fedot (>=0.7.3,<0.8.0) requires sktime (0.16.1).
So, because sktime (0.16.1) requires Python <3.12,>=3.7
 and <my package> depends on fedot (^0.7.3), version solving failed.
```

Could you consider upgrading `sktime`'s version in requirements, so that fedot can be installed on python 3.12 safely?

**Comment by DRMPN** [comment]
@e-kondr01 Thanks for opening the issue! Can you please tell me what operating system you are using?

**Comment by e-kondr01** [comment]
I'm using Ubuntu 20.04 and Poetry to manage python dependencies.
However, that has nothing to do with the issue.
In Fedot's requirements:
https://github.com/aimclub/FEDOT/blob/master/requirements.txt#L17
exact version of `sktime==0.16.1` is pinned.
However, `sktime` supports python 3.12 only from `sktime==0.24.0`:
https://github.com/sktime/sktime/releases/tag/v0.24.0
https://github.com/sktime/sktime/commit/8b4737bfd6af50143d85f967f968cccc4dd3108b
