### ISSUE TITLE
Implement oversampling/undersampling for the input dataset

### ISSUE THREAD

**Issue by nicl-nno** [aimclub/FEDOT#128]
- Derive oversampling/undersampling functions from existing libaries
- Implement automated data preprocessing for InputData as a part of Fedot API
- Run experiments to prove the efficiency of oversampling/undersampling for the composite models.

**Comment by nicl-nno** [comment]
@Dreamlone 

А oversampling/undersampling можно реализовать как блоки предобработки? Или менять число строк нельзя?

**Comment by Dreamlone** [comment]
Да, это изменение количества строк предусмотрено в текущей версии операций предобработки. Как пример подобной реализации можно использовать [RANSAC](https://github.com/nccr-itmo/FEDOT/blob/master/fedot/core/operations/evaluation/operation_implementations/data_operations/sklearn_filters.py#L74) алгоритм, см. в [sklearn_filters](https://github.com/nccr-itmo/FEDOT/blob/master/fedot/core/operations/evaluation/operation_implementations/data_operations/sklearn_filters.py). Просто стоит следить за корректностью изменения индексов объектов в таблице. И, полагаю, стоит унаследовать новые операции от FilterImplementation класса.

**Comment by valer1435** [comment]
Не закрыто с реализацией resample?
