### ISSUE TITLE
[Bug]: No "last updated" date for edited PEP8 Action comment 

### ISSUE THREAD

**Issue by DRMPN** [aimclub/FEDOT#1306]
Github Action for PEP8 style check doesn't produce "last updated" date for edited comment.

## Expected Behavior
When a PEP8 comment is edited, the "last updated" date changes.

## Current Behavior
It does not.
![image](https://github.com/aimclub/FEDOT/assets/61294398/58e558bd-5b68-4c4f-b294-d76a8e2b0a31)

## Possible Solution
Find the solution and change part of the broken code in [autopep8 action](https://github.com/aimclub/FEDOT/blob/master/.github/workflows/autopep8.yml)

## Steps to Reproduce
1. Open Pull Request with broken formatting
2. Wait for error comment from github-actions bot
3. Write `/fix-pep8`
4. Wait for bot to make commit with changes
5. Check the updated comment

## Context [OPTIONAL]
Pull Requests

**Comment by nicl-nno** [comment]
Not FEDOT-related
