### ISSUE TITLE
Add README for the examples

### ISSUE THREAD

**Issue by nicl-nno** [aimclub/FEDOT#298]
We have a lot of examples in FEDOT now. However, it is hard to understand the scope of each example.

So, the README file for examples section with short description of each example can be added.

See https://github.com/awslabs/autogluon/tree/master/examples/image_classification as an example of second-level README implementation.

**Comment by J3FALL** [comment]
I also suggest to re-organize the structure of examples. Some scripts can be moved to a separate directory.
![image](https://user-images.githubusercontent.com/7864250/118822432-d44d4f00-b8c0-11eb-95a3-f224aec49c79.png)

**Comment by nicl-nno** [comment]
In the same issue, the tests should be added for each example.
Also, the problem noted in https://github.com/nccr-itmo/FEDOT/pull/291#discussion_r636431255 should be investigated.
