### ISSUE TITLE
Investigate new data operations for feature engineering and ensembling

### ISSUE THREAD

**Issue by J3FALL** [aimclub/FEDOT#312]
- Add simple Ensembling methods, such as TopModel, WeightedEnsemble and AverageEnsemble
- Discover the best practises of FE methods for classification/regression of table-like datasets
- Perform the experiments with expert-based feature engineering as a separate DataOperation blocks
- Think about special presets of models/operations for classification/regression
- Try feature generation methods, for instance, like [featuretools](https://github.com/alteryx/featuretools)

**Comment by nicl-nno** [comment]
"Importance Cut off" also effectiventess also can be analysed

**Comment by MAGLeb** [comment]
План действий:

- [x] 1. Добавить CatBoost, LightGBM + гиперпараметры
- [x] 2. Посмотреть и составить примерный алгоритм/схему, как происходит feature engineering в LAMA (https://github.com/nccr-itmo/FEDOT/tree/LAMA-manula-pipeline)
- [x] 3. изучить в чем разница pipeline между LAMA - FEDOT
- [ ] 4. Прогнать LAMA на бенчмарках (см. https://github.com/nicl-nno/automlbenchmark/blob/master/frameworks/FEDOT/exec.py) добавить необходимую разницу в FEDOT
- [ ] 5. научить композер создавать такие (или лучшие пайплайны)

**Comment by MAGLeb** [comment]
На одном датасете были обучены оба фреймфорка. Для обоих фреймворков прогнали обучение по 8 раз и усреднили метрики:

**FEDOT**

**_AUC_**
_5 MINUTES_
train: 0.7995216483735391
test: 0.7141597316576087

_10 MINUTES_
train: 0.8050606503972741
test: 0.7121297554347826

_20 MINUTES_
train: 0.7735015904571719
test: 0.723378269361413

**LAMA**

**_AUC_**
_40 seconds_
0.7059763219386357
0.7197197690217392

Для FEDOT необходимо было делать предварительную предобработку даты и категориальных признаков.

**Comment by graceyangfan** [comment]
will any genetic feature engineering between the multivariable features ,such as feature1*lag(feature2,10).Since I find there is a genetic algorithm  
in fedot.

**Comment by nicl-nno** [comment]
We did not plan to design the features by GA itself. However, we use existing feature generators like poly_features and tune it's hyperparameters during evolution and tuning.
