### ISSUE TITLE
Iterative out-of-sample forecasting of time series using API

### ISSUE THREAD

**Issue by nicl-nno** [aimclub/FEDOT#333]
In current version, out-of-sample-foracast for time series is implemented in out_of_sample_ts_forecast function.
However, it cannot be used with FEDOT API.

The support of in-sample and out-of-sample forecasting should for simple and multivariate time series should be implemented in forecast method of API.

**Comment by nicl-nno** [comment]
@YamLyubov это можно считать решенным в твоем PR-е?

**Comment by YamLyubov** [comment]
Получается, что да. Только out-of-sample реализован в предикте
