### ISSUE TITLE
Forecasting smoothed time series

### ISSUE THREAD

**Issue by Dreamlone** [aimclub/FEDOT#347]
A possible improvement of the time series smoothing operation is proposed. Below is example of applying smoothed operation
![image](https://user-images.githubusercontent.com/52418437/124166545-a0fb0400-daab-11eb-858a-ad700a10316d.png)

Currently, the implementation of smoothing allows modifying only the "features" time series (features field in InputData/OutputData). But it does not change the target. Changing target as part of smoothing can also allow us to build more efficient pipelines (probably)

**Comment by nicl-nno** [comment]
А почему smoothing влияет на target, а не просто выдает сглаженный predict?

**Comment by Dreamlone** [comment]
Возможно не так описал (сам запутался, сейчас переформулирую и изменю описание). Если подробно: 1) есть исходный временной ряд (features) и этот же самый исходный временной ряд (target). После операции сглаживания, сглаженный временной ряд из features переходит в features для следующего узла, target временной ряд при этом остаётся без изменений. То есть преобразование осуществляется только над features.

2) Операция lagged. Берёт сглаженные features и исходный target и сопоставляет их. Я подумал и хотел обсудить, раз у нас появилась возможность использовать разные target'ы в одном пайплайне, то лучше было бы в операции lagged сопоставлять именно сглаженные features со сглаженным target'м. Вроде вся идея сглаживания, что мы можем прогнозировать более спокойный временной ряд, без лишнего шума. А тут мы признаки то подправили, а вот target как был шумным, так и остался. 

Ну и так как здесь тег discuss, можно оставить и как есть.

**Comment by nicl-nno** [comment]
>лучше было бы в операции lagged сопоставлять именно сглаженные features со сглаженным target'м

Ну кмк если это и делать - то как отдельный вариант операции. Т.к. сглаживание только признаков вполне может иметь позитивный эффект, т.к. уменьшает шум (а предсказание модели все равно шум в target не предскажет)

**Comment by kasyanovse** [comment]
Сходу приходят следующие минусы введения нового smoothing со сглаживанием таргета:

1. Любое сглаживание добавляет некоторый лаг в данные. Если таргет не трогать, то модель/узел может прекрасно обучиться работать с этим лагом. Если сгладить таргет, то модель/узел перенесет этот лаг в предикт, что потенциально приведет к ухудшению метрик.
2. Да, где-то дальше в пайплайне этот лаг может быть исправлен другим узлом, но может быть и не исправлен.
3. Встает проблема распространения правильного таргета по пайплайну и подавления распространения сглаженного (я не вкурсе, может быть проблемы нет)
4. Введение нового узла/нового параметра узла приведет к увеличению размерности области поиска оптимального пайплайна.

Плюсов я не вижу. Для поиска плюсов нужно исследование, то есть время и труд.

Так как ожидаемые плюсы от внедрения такой фичи не совсем ясны, но вполне ясны минусы, я бы предложил отказаться от этой идеи.
