### ISSUE TITLE
Technical debt and refactoring

### ISSUE THREAD

**Issue by J3FALL** [aimclub/FEDOT#37]
Доработки и рефакторинг после показа:
1. ~Отрицательные значения метрик (см. ROC AUC): добавить property для метрик, которые передаются алгоритму оптимизации.~
2. ~Хранение reference_data в chain - тут нужно подумать.~
3. ~Обработка Nan-ов в EvaluationStrategy~.
4. ~Дублирование кода в models. Возможно, добавить прослойку для SKLearn/ML Model~.
5. TBA

**Comment by J3FALL** [comment]
14. Get rid of NodeGenerator in core.

**Comment by nicl-nno** [comment]
15. Преобразовать гиперпараметры в JSON

"Все-таки, привычнее видеть такие около hardcode-штуки во внешних конфигах.
Возможно, какой-нибудь продвинутный json-парсер для питона позволит там вынести эти параметры из скрипта, а также решит полностью или частично проблемы с его валидацией."

**Comment by J3FALL** [comment]
16. Улучшить тесты на тюнинг.
"Кажется, я однажды уже озвучивал идею про тестирование тюнеров - делать заведомо плохие цепочки для конкретного датасета. Например, можно для тестовой цепочки установить некоторые совсем нереалистичные значения.
Однако, все равно не гарантируется, что точно найдется за заданное время работы теста решение > исходного.
Над этим можно подумать на досуге - как грамотнее тестировать тюнеры."

**Comment by nicl-nno** [comment]
17.

Refactor model test in https://github.com/nccr-itmo/FEDOT/blob/master/test/models/test_model.py 

It should be runned for each model in repository, not just manually added in the test.

**Comment by J3FALL** [comment]
18. Suggest the more "native" tags for AtomizedModel in ModelTypesRepository

**Comment by nicl-nno** [comment]
I think it can be closed as obsolete.
