### ISSUE TITLE
Mac ARM support

### ISSUE THREAD

**Issue by Robiemaan** [aimclub/FEDOT#486]
I'm running into several issues trying to get FEDOT set up on an M1 Mac.
Are you guys planning on supporting Mac ARM?

**Comment by nicl-nno** [comment]
Hi! 

Are your issues connected with FEDOT itself or it's dependencies only?

**Comment by Robiemaan** [comment]
Sorry, I should've been more specific:
When I try to install with conda, it doesn't find fedot at all:
Current channels:
  - https://conda.anaconda.org/conda-forge/osx-arm64
  - https://conda.anaconda.org/conda-forge/noarch

When I try pip, I get dependency issues with deap:
ERROR: No matching distribution found for deap>=1.3.*

Note: I use conda virtual environments like this:
conda create --name venv python=3.9.5

Should I be using another version of python? - I've had trouble using 3.8.10 because of numpy/pandas issues on M1.

**Comment by gdamianakos** [comment]
> Sorry, I should've been more specific: When I try to install with conda, it doesn't find fedot at all: Current channels:
> 
> * https://conda.anaconda.org/conda-forge/osx-arm64
> * https://conda.anaconda.org/conda-forge/noarch
> 
> When I try pip, I get dependency issues with deap: ERROR: No matching distribution found for deap>=1.3.*
> 
> Note: I use conda virtual environments like this: conda create --name venv python=3.9.5
> 
> Should I be using another version of python? - I've had trouble using 3.8.10 because of numpy/pandas issues on M1.

check issue #998
I provided a clean solution that was reproduced in several machines
[https://github.com/aimclub/FEDOT/issues/998](https://github.com/aimclub/FEDOT/issues/998)

**Comment by valer1435** [comment]
Closed as obsolete (see https://github.com/aimclub/FEDOT/issues/998)
