### ISSUE TITLE
implementing tsfresh as a node in FEDOT

### ISSUE THREAD

**Issue by astrogilda** [aimclub/FEDOT#552]
`tsfresh` gives access to a whole range of features engineered specifically for time-series problems, and also has sensible feature selection algorithms built in. Is there a way to use tsfresh as a node in FEDOT?

**Comment by nicl-nno** [comment]
Hello,

Yes, you can implement tsfresh as custom model in FEDOT or add it to model repository.
 
However, is is most suitable for time series classification task, that is now fully supported yet.

**Comment by nicl-nno** [comment]
Now, TS classification is implemented in https://github.com/aimclub/Fedot.Industrial
