### ISSUE TITLE
Implement support of one-core execution

### ISSUE THREAD

**Issue by nicl-nno** [aimclub/FEDOT#602]
Current 1-thread setup can raise the following problem since the sklearn models are parallelable by default:

![image](https://user-images.githubusercontent.com/5711814/158979826-c059407c-b487-4f0b-a0b2-0c66a104c39a.png)

**Comment by kasyanovse** [comment]
Есть код для воспроизведения?
Если нет, то предлагаю закрыть.

**Comment by kasyanovse** [comment]
Закрыто, так как для большинства моделей задано `n_jobs=1`. Они больше не параллелятся. Также `joblib` на текущий момент отлично отрабатывает всякие косяки и баги с мультипотоком (проверено).
