### ISSUE TITLE
Add transformers to the pipeline

### ISSUE THREAD

**Issue by hemangjoshi37a** [aimclub/FEDOT#677]
Add transformers to the pipeline
[https://hjlabs.in/](https://hjlabs.in/)

**Comment by nicl-nno** [comment]
Hello, hemangjoshi37a.

Please describe the case that you want to solve using transformer models in FEDOT.

**Comment by hemangjoshi37a** [comment]
I want to do time series forecasting of power plant and electrical substations. Also I want to use it in some language models.

**Comment by nicl-nno** [comment]
Partially implemented in https://github.com/aimclub/Fedot.Industrial
