### ISSUE TITLE
Abstract GraphOptimiser from FEDOT

### ISSUE THREAD

**Issue by gkirgizov** [aimclub/FEDOT#713]
Meta-issue for tracking progress about our *Dream*: making an ecosystem of application domains around one abstract and modular GraphOptimiser.
After this issue we could begin transition of EPDE/BAMT/Gefest and possibly others onto new architecture; while FEDOT will be using this GraphOptimiser in the domain of AutoML. 

These are the steps that I see as necessary for this:
- [x] aimclub/FEDOT#608 
- [x] aimclub/FEDOT#705 
- [x] aimclub/FEDOT#706 
- [ ] Likely needed a better definition of Composer / ComposerBuilder and separation of their responsibilities
- [x] Define responsibilities of the base GraphOptimiser, especially wrt EvoGraphOptimiser. Maybe it will be just an abstract interface, maybe it will handle some infrastructural functions (logging/timing/history/stop conditions).
Mostly closed by aimclub/FEDOT#787
- [x] aimclub/FEDOT#850
- [x] aimclub/GOLEM#27
- [x] aimclub/FEDOT#866
- [x] aimclub/FEDOT#967 
- [x] aimclub/FEDOT#969 

You can link to this issue any thoughts/features/requirements you have in mind about GraphOptimiser.

**Comment by nicl-nno** [comment]
[This](https://github.com/nccr-itmo/FEDOT/pull/660) PR also can be useful, since it describes the features required for integration with GEFEST and other non-graph solutions.

**Comment by gkirgizov** [comment]
![Текущая архитектурка](https://user-images.githubusercontent.com/10994117/172602027-b81a904b-93e4-48bd-8a9a-1bc830ab7c68.png)

**Comment by gkirgizov** [comment]
closed with #989
