### ISSUE TITLE
Redundant logging at launch in jupyter notebook

### ISSUE THREAD

**Issue by Dreamlone** [aimclub/FEDOT#748]
A lot of messages appear during launch

Example: 
```
from fedot.api.main import Fedot
model = Fedot(problem='regression', timeout=1)

# fit model with AutoML
train_columns = df.columns[:-1]
obtained_pipeline = model.fit(features=df[train_columns], target=df['target'])
```

![image](https://user-images.githubusercontent.com/52418437/176186666-5b60eccc-0fb9-4dc2-94f4-231d72edaa50.png)

**Comment by kasyanovse** [comment]
На текущий момент (с учетом https://github.com/aimclub/FEDOT/pull/1174), проблема только в `FutureWarning`.

**Comment by Dreamlone** [comment]
В таком случае можно данный тикет закрыть (сделай re-open если не согласен). Ворнинги я точно к этому issue не относил
