### ISSUE TITLE
unreadable docs, misprints

### ISSUE THREAD

**Issue by DenisSidoren** [aimclub/FEDOT#762]
in this case - sphinx unrecognized structure elements
![image](https://user-images.githubusercontent.com/70846761/177559843-bf5b7264-4931-4330-aad7-9090ae8cd472.png)

In this case - repeats of the same information --> unreadable and complicated for users
![image](https://user-images.githubusercontent.com/70846761/177560078-3f576093-6a01-43e5-b9af-7df10dac329f.png)

Target view: 

![image](https://user-images.githubusercontent.com/70846761/177559513-d1f881f3-1b5a-47aa-94fe-efbf0fafc918.png)

**Comment by nicl-nno** [comment]
@DenisSidoren это можно считать решенным?
