### ISSUE TITLE
Time-series related bugs

### ISSUE THREAD

**Issue by Dreamlone** [aimclub/FEDOT#821]
Some bugs arised during time series benchmark experiments (the post will be updated periodically):

```
OptimisationTimer - Composition time: 1.8 min
Exception "no default __reduce__ due to non-trivial __cinit__" raised. Skip time series temp for horizon 10.
```

Code to launch: https://github.com/ITMO-NSS-team/pytsbe/blob/fedot-upd/experiment_launch.py

**Comment by kasyanovse** [comment]
Closed up due to pytsbe does not support current Fedot version.
