### ISSUE TITLE
Abstract fitted models cache functionality from EvaluationDispatcher

### ISSUE THREAD

**Issue by gkirgizov** [aimclub/FEDOT#845]
The aim is to allows other cache implementations, for example, for NAS
Tasks:
- [ ] Introduce Cache interface that works per-graph (as opposed to OperationsCache that works per-node)
- [ ] Implement or find cache implementation suitable for large models (e.g. as in NAS)
- [ ] Extract RemoteEvaluator usage as remote cache implementation (currently it is hardcoded into EvaluationDispatcher)

This issue came out of our discussion with @staeros  about how to implement cache for NAS

**Comment by nicl-nno** [comment]
> Implement or find cache implementation suitable for large models (e.g. as in NAS)

Если я правильно понимаю, то для NAS реализация кэша может быть весьма примитивной - можно просто в памяти держать пары descriptive_id - фитнес. Т.к. в отличие от пайплайнов нет блоков, которые нужно кэшировать отдельно.

**Comment by gkirgizov** [comment]
Есть подозрение, что очень легко может понадобиться выгрузка на диск. Одна нейросетка легко может пару гб занимать. Это либо самим реализовать, либо, вероятно, какую-то готовую реализацию такого кэша можно подтянуть, какой-нибудь key-value LRU cache с выгрузкой на диск неиспользуемых

> > Implement or find cache implementation suitable for large models (e.g. as in NAS)
> 
> Если я правильно понимаю, то для NAS реализация кэша может быть весьма примитивной - можно просто в памяти держать пары descriptive_id - фитнес. Т.к. в отличие от пайплайнов нет блоков, которые нужно кэшировать отдельно.

**Comment by nicl-nno** [comment]
>Есть подозрение, что очень легко может понадобиться выгрузка на диск. Одна нейросетка легко может пару гб занимать.

А зачем это именно для кэширования в NAS-е? Там нужно именно именно сохранение самих сетей, а не фитнеса?

**Comment by gkirgizov** [comment]
> А зачем это именно для кэширования в NAS-е? Там нужно именно именно сохранение самих сетей, а не фитнеса?

Да, тут речь именно про кэширование обученных моделей

**Comment by nicl-nno** [comment]
>Может быть, с нейросетками тоже имеет смысл кэшировать параметры слоев (как отдельных нод), если их предки не изменились. Наверное, это может заметно ускорить обучение. @staeros, что скажешь насчет всего этого?

Если так можно делать - то да, тогда смысл есть.

**Comment by gkirgizov** [comment]
Not planned, maybe will reiterate later when need arises
