### ISSUE TITLE
Make explicit notation for initial assumptions and final choices in OptHistory

### ISSUE THREAD

**Issue by MorrisNein** [aimclub/FEDOT#846]
There's a need to make `OptHistory` class more clear and testable. 

To specify, `OptHistory.individuals` is a list of generations, each of them is the list of individuals. There are two implicit agreements:
1) to store initial assumptions as generation 0, 
2) to store the final choices as the last generation.

The first agreement can easily be broken, it is not covered by tests.
The second agreement is already broken by recent changes, there's also no tests for it.

The following changes are required:

1. OptHistory should contain the individuals chosen for final tuning _again_ (fix).
2. OptHistory should refer to the **initial assumptions** and the **final choices** via explicit names (for test and interface purposes).
3. There should be a test that validates newly-generated histories to contain these named entities (test coverage of the fix).

**Comment by gkirgizov** [comment]
Можно в описании пояснить, для чего это требуется? Описано "что", но неочевидно "зачем" (особенно пункт 2)

**Comment by MorrisNein** [comment]
> Можно в описании пояснить, для чего это требуется? Описано "что", но неочевидно "зачем" (особенно пункт 2)

Обновил описание
