### ISSUE TITLE
Refactor utilities

### ISSUE THREAD

**Issue by nicl-nno** [aimclub/FEDOT#860]
The utilities module is duplicated now:

![image](https://user-images.githubusercontent.com/5711814/188181347-36ed4817-cff6-434d-ac4d-1ed66f5ff7cb.png)

**Comment by kasyanovse** [comment]
Not actual for FEDOT.
Create new issue for GOLEM https://github.com/aimclub/GOLEM/issues/173.

![image](https://github.com/aimclub/FEDOT/assets/25120268/61f1da9d-c5ca-4153-85e1-0473ec87bbee)
