### ISSUE TITLE
incorrect fitness plot for NAS

### ISSUE THREAD

**Issue by staeros** [aimclub/FEDOT#867]
There is some issue with fitness plot for NAS. Fitness graph is sometimes built incorrectly e.g. later generations are on the plot earlier than more earlier generations. @MorrisNein 
![Figure_1](https://user-images.githubusercontent.com/73821003/188920277-3b2e80cd-896d-49fc-8dc0-066d73fa2c9c.png)

**Comment by staeros** [comment]
Also, when several individuals have the same fitness, it does not show up on the graph.
![photo_2022-09-07_18-16-53](https://user-images.githubusercontent.com/73821003/188921569-980eb75d-ff20-461f-af50-382f9311ed5c.jpg)

**Comment by MorrisNein** [comment]
Помнится, что там неправильно сгенерилась история. Ещё это могло быть связано с распараллеливанием, и в этом направлении мы много проблем уже порешали.

В общем, так ни разу и не воспроизвелось это. @staeros, поправь, если не так

**Comment by nicl-nno** [comment]
Resolved
