### ISSUE TITLE
Documentation: FEDOT Features

### ISSUE THREAD

**Issue by nicl-nno** [aimclub/FEDOT#879]
Add the structured description of main features important for end user and compare with other frameworks

**Comment by nicl-nno** [comment]
@IIaKyJIuH 

Нужно в обозримом будущем дописать этот текст - поэтому взял бы на себя. 
Ты по этой задаче что-то начинал уже писать, чтоб можно было использовать?

**Comment by IIaKyJIuH** [comment]
@nicl-nno 

Немного написал [в ветке](https://github.com/aimclub/FEDOT/tree/879_doc_features):
* [introduction/*](https://github.com/aimclub/FEDOT/tree/879_doc_features/docs/source/introduction), сделал в этом месте папку fedot_features, которая расширяет прежний один файл `fedot_features.rst`
* [basics/concepts.rst](https://github.com/aimclub/FEDOT/blob/879_doc_features/docs/source/basics/concepts.rst#enroll-beta), здесь частично куски из `fedot_features.rst`

**Comment by nicl-nno** [comment]
О, это здорово. 

Доведи тогда до какого-то промежуточного состояния и создай PR - я в него и добавлю свои изменения.
