### ISSUE TITLE
Documentation: Main concepts

### ISSUE THREAD

**Issue by nicl-nno** [aimclub/FEDOT#881]
The high-level concepts of FEDOT (since it's differs from existing AutoMLs) should be described to user.

**Comment by nicl-nno** [comment]
@ChrisLisbon мысли по гибридному AutoML тоже можно в рамках этой задачи изложить (в дополнение к статье).

**Comment by valer1435** [comment]
https://github.com/aimclub/FEDOT/issues/879 случайно не закрыто здесь?
