### ISSUE TITLE
Better early stopping

### ISSUE THREAD

**Issue by nicl-nno** [aimclub/FEDOT#899]
Current issues:

- early_stopping_generations param is poplulation-based, not time-based.
- early_stopping_generations is desribed incorrectly in docstring (as 'stopping_after_n_generation')

Ideas:
If early_stopping_generations is 'auto', that estimate it as in time-based manner as: 0.33*composing_timeout. The minimal number of generations is 5.

**Comment by gkirgizov** [comment]
То есть вместо количества стагнирующих итераций отслеживать время стагнирования? Звучит неплохо, имеет смысл. Но  хотелось бы сохранить возможность указывать как количество итераций.
(Пожалуй, правильнее назвать `early_stopping_iterations`)

**Comment by nicl-nno** [comment]
Да, тут оба варианта лучше иметь.
