### ISSUE TITLE
Suggested minor improvements for FEDOT API

### ISSUE THREAD

**Issue by MorrisNein** [aimclub/FEDOT#906]
Some convenience improvements should be performed at any time: 

- [x] Allow `Fedot.fit` to get path to `features` and `target` via `Path` objects.
- [x] Write explicit docstring for `Fedot.fit`.
- [x] Use generic type `FeaturesType` in `Fedot.fit` annotation.
- [x] Rename `stop_after_n_generations` -> `early_stopping_generations` [here](https://github.com/nccr-itmo/FEDOT/blob/master/fedot/api/main.py#L75). Also see: https://github.com/nccr-itmo/FEDOT/issues/899
- [x] https://github.com/nccr-itmo/FEDOT/issues/873
- [x] https://github.com/nccr-itmo/FEDOT/issues/874 (Possibly linked to the above)

**Comment by gkirgizov** [comment]
Предложу еще заменить имена пресетов в constants.py на нормальный Enum

**Comment by nicl-nno** [comment]
> Предложу еще заменить имена пресетов в constants.py на нормальный Enum

На мой взгляд не стоит enum-ы выносить в какие-то внешние интерфейсы. На практике в python-фреймворках так делают редко. Ну и тянет за собой лишние импорты.

**Comment by MorrisNein** [comment]
> > Предложу еще заменить имена пресетов в constants.py на нормальный Enum
> 
> На мой взгляд не стоит enum-ы выносить в какие-то внешние интерфейсы.

К слову, необязательно обязывать внешний интерфейс использовать Enum. А вообще у Python, кмк, есть идеальный выход для данной ситуации:

![image](https://user-images.githubusercontent.com/57573631/194698402-0fbd20b2-d4b4-4152-9497-6f9140bfdc46.png)

Т.е. пока мы сравниваем через `==`, для нас строковая переменная будет равнозначна элементу перечисления.
