### ISSUE TITLE
Fedot's bugs in timeseries problem

### ISSUE THREAD

**Issue by aPovidlo** [aimclub/FEDOT#944]
There are bugs in composition which pop up with `logging_level=logging.DEBUG`:

* `PipelineObjectiveEvaluate - Continuing after pipeline fit error <Per-column arrays must each be 1-dimensional> for graph: ((/n_lagged_{'window_size': 10};)/n_locf_{'part_for_repeat': -1};;/n_glm_{'family': 'gaussian', 'link': 'identity'};)/n_ridge_{}`
* `PipelineObjectiveEvaluate - Continuing after pipeline fit error <endog must be 1-dimensional> for graph: ((/n_sparse_lagged_{'window_size': 10, 'n_components': 0.5, 'sparse_transform': True, 'use_svd': False};)/n_ets_{'error': 'add', 'trend': None, 'seasonal': None, 'damped_trend': False, 'seasonal_periods': 7};;/n_glm_{'family': 'gaussian', 'link': 'identity'};)/n_ridge_{}`

And in general, the quality of the pipelines are decreased. It was discovered that numbers of generations is pretty small even if `timeout = 40` for a simple datasets.

Script for repeating the bug:
```
path_to_ts = os.path.join(f'{fedot_project_root()}', 'examples/data/ts', 'ts_sea_level.csv')

time_series = pd.read_csv(path_to_ts)
time_series['Date'] = pd.to_datetime(time_series['Date'])

len_forecast = 250

task_parameters = TsForecastingParams(forecast_length=len_forecast)
task = Task(TaskTypesEnum.ts_forecasting, task_parameters)

input_data = InputData(
    idx=time_series['Date'].values,
    features=np.array(time_series['Level']),
    target=np.array(time_series['Level']),
    task=task,
    data_type=DataTypesEnum.ts
)

train_data, test_data = train_test_data_setup(input_data)

model = Fedot(problem='ts_forecasting',
              task_params=task.task_params,
              timeout=15,
              logging_level=logging.DEBUG
)

pipeline = model.fit(train_data)
```

**Comment by valer1435** [comment]
Горизонт 250 - уж слишком много для такого примера. Нашел сейчас в пайплайне rfr, который обучался на 500 признаков. А учитывая горизонт - таких моделей надо было строить 250 штук, что просто висло

**Comment by nicl-nno** [comment]
Можно сделать чтобы по-умолчанию фактический горизонт был не больше какого-то разумного значения - а дальше до заданного горизонта прогнозировалось итеративно.

**Comment by aPovidlo** [comment]
> Горизонт 250 - уж слишком много для такого примера. Нашел сейчас в пайплайне rfr, который обучался на 500 признаков. А учитывая горизонт - таких моделей надо было строить 250 штук, что просто висло

Опирался на данный [пример](https://github.com/ITMO-NSS-team/fedot-examples/blob/main/notebooks/latest/3_intro_ts_forecasting.ipynb). Возможно, для rfr это действительно много

**Comment by nicl-nno** [comment]
Но для примера действительно можно просто уменьшить.

**Comment by aPovidlo** [comment]
@valer1435 А какой следует поставить горизонт тогда?

**Comment by aPovidlo** [comment]
> > @valer1435 А какой следует поставить горизонт тогда?
> 
> Поставил 10. Странно, что попадаются операции, которых я никогда не видел и даже убирал из пла моделей (clstm, например). Поэтому долго работает

Понял, тогда запущу тетрадку позже после фикса моделей

**Comment by nicl-nno** [comment]
@valer1435 @aPovidlo можно ли закрывать?
