### ISSUE TITLE
Separate visualization module on 2 parts: universal for graphs and specific for pipelines

### ISSUE THREAD

**Issue by gkirgizov** [aimclub/FEDOT#967]
Some viz methods require knowledge only about graph structure, node names and fitness/history.
Some methods seem to be Pipeline-specific. Like those that rely on OperationRepository.

Such cases must be analyzed and either abstracted to be universal or or separated as specific. 
That's required for GOLEM separation.

**Comment by MorrisNein** [comment]
Closed by #980
